STANDARD_BASE_PRICE = 13
PREMIUM_BASE_PRICE = 15
PLATINUM_BASE_PRICE = 17

LEVEL_HIGHSCHOOL_DELTA = 0
LEVEL_COLLEGE_DELTA = 2
LEVEL_UNIVERSITY_DELTA = 3
LEVEL_MASTERS_DELTA = 4
LEVEL_PHD_DELTA = 5

MESSAGE_TYPE_USER_MESSAGE = 1
MESSAGE_TYPE_STATUS_CHANGE = 2
